name: dependency scan

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  fpvs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: reqs
        run: |
          python -m pip install wheel
          python -m pip wheel -r requirements.txt --wheel-dir=vendor

      - name: fpvs scan
        run: |
          python -m pip install fpvs
          git clone https://gitlab.com/gitlab-org/security-products/gemnasium-db.git
          fpvs-scan --verbose

  pip-audit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: pip install
        run: |
          python -m pip install -r requirements.txt
          python -m pip install .

      - uses: pypa/gh-action-pip-audit@v1.0.8
        with:
          inputs: requirements.txt
